### ISSUE TITLE
[Feature 0] Initial Folder Structure 

### ISSUE THREAD

**Issue by moonsdust** [CSC207-2022F-UofT/course-project-todo-find-a-team-name#10]
The purpose of this issue is to get an initial folder structure for our project. 

Will figure out folders needed later

**Comment by michaelhsj** [comment]
We can move main/Main.java within src so that we instead have src/Main.java, but everything else seems good!

**Comment by Kai15116** [comment]
I just noticed that all source code should be inside src/main/java. So I think entities, example_usecase, screens, and Main.java should all be moved to src/main/java.

**Comment by moonsdust** [comment]
@Kai15116 Yeah maybe we should move them. I think someone should do that during the lab or beforehand
