### ISSUE TITLE
[Feature 9] Main Menu UI 

### ISSUE THREAD

**Issue by moonsdust** [CSC207-2022F-UofT/course-project-todo-find-a-team-name#23]
Creating the UI for the main menu, which consists of buttons such as: 
- importing
- displaying timetables
- (LoadCourse LoadConstraint Screen) Entering CourseCode and Constraints. [Added by Hans]
- generating a new timetable (Need to check with someone on this)
- editing timetable

**Comment by hanshhh** [comment]
Creating the UI for the main menu, which consists of buttons such as:

- importing
- displaying timetables
- (LoadCourse LoadConstraint Screen)Entering CourseCode and Constraints. 
- generating a new timetable (Need to check with someone on this)
- editing timetable

-
