### ISSUE TITLE
!!! Read This Before Submitting Future Pull Request and Reviewing Pull Requests !!!

### ISSUE THREAD

**Issue by moonsdust** [CSC207-2022F-UofT/course-project-todo-find-a-team-name#55]
Based on our TA's comments, for submitting future pull requests: 
- Explain more in details the changes you have made
- Explain how your changes fits into the overall project (fixed a bug/made an enhancement)
- Any design decisions you made (Ex: related to SOLID principles, clean architecture, design patterns, etc.)

For future pull request reviews, try to have discussion when reviewing code.

**Comment by YahyaElgabra** [comment]
since all pull requests are completed, this issue is complete
