### ISSUE TITLE
[Feature 0] Base Features

### ISSUE THREAD

**Issue by michaelhsj** [CSC207-2022F-UofT/course-project-todo-find-a-team-name#9]
Implementing crucial entities that will be used in all features.

**Comment by moonsdust** [comment]
Entities: 
- [x] Session: Emily
- [x] Course (Abstract): Michael Prime
     - [x] TimetableCourse:  Michael Hui
     - [x] CalenderCourse: Michael Hui
- [x] Section: Kai 
- [x] Block: Yahya
- [x] Timetable: JD (Jacob)
- [x] Constraints: Hans
